services:
  murrfecto-back:
    env_file:
      - ./server/.env
    build:
      context: ./
    volumes:
      - static-murrfecto:/server/images
    ports:
      - "3000:3000"

networks:
  localnet:
    external: true
    name: localnet

volumes:
  static-murrfecto:
